FROM grafana/grafana:6.7.1
ADD datasource.yml /etc/grafana/provisioning/datasources
ADD dashboards /etc/grafana/provisioning/dashboards
ADD dashboard.yml /etc/grafana/provisioning/dashboards
ADD grafana.ini /etc/grafana

